### ISSUE TITLE
Support building new images with different Python versions in the CI

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-oci-images#109]
We want to support older versions of Python in the CI for release branches of pulpcore and plugins. We built a `python36` image of pulp_ci_centos but optimally it would be nice to have the CI build different images with different versions of Python.

**Comment by mdellweg** [comment]
Either that, or we provide a pulp-ci-base image suited for each minor pulpcore release, tagged e.g. `pulp/pulp-ci-base:3.14`.
And the python version used would depend on the pulpcore release.

**Comment by mikedep333** [comment]
We do not think this is needed.

Right now recent branches are based on CentOS 8 / Python 3.8. We're about to make 3.20 and later based on CentOS 9 / Python 3.9. Each Pulp 3.y branch will have its own acceptable version of CentOS and Python.
