### ISSUE TITLE
RQ worker count

### ISSUE THREAD

**Issue by keilr** [pulp/pulp-oci-images#122]
- is it already possible to specify the number of RQ workers? (settings.py option or environment variable)
- if not: could it be added to the init script?

**Comment by dralley** [comment]
edit: Ignore this, I'm wrong.

**Comment by mdellweg** [comment]
> since the dockerfile runs the ansible installer

That would be news to me. The OCI-images have their own service files based on s6 and are tailored with 2 workers. We know that this is quite inflexible, but as a cost for being easy to deploy for evaluating pulp. I'd recommend using a full ansible installation or the pulp-operator for production installations.

**Comment by dralley** [comment]
You are right, I should have checked.  Not sure why I had that "recollection" come to mind.  Probably because we do something like that with the CI..

**Comment by keilr** [comment]
thanks a lot for your feedback. We will continue to use the all-in-one image until pulp-operator is production-ready and our on-premise container platform is set up. Until then, we have to live with the limitations of the all-in-one image (+ podman).

We try to avoid ansible pulp_installer and prefer containerized solutions. In the past, we had very bad experiences with such complex ansible deployments (e.g. Ansible Tower, or Foreman Forklift). Our RHEL-base-Linux-Images are hardened (CIS-Benchmark) and the servers don't have direct internet access which has often led to errors. (In the pulp_installer docs, RHEL isn't even listed as a supported OS.) But don't get me wrong, the pulp_installer looks very clean and good documented. It's just our preference to use containers to minimize integration effort.

**Comment by mdellweg** [comment]
If you don't mind, it should be possible to adjust the container assets and the containerfile on a local branch on top of the provided images. Maybe it's as simple as adding some symlinks for the service files.

**Comment by keilr** [comment]
ok, thanks a lot for the hint.
