### ISSUE TITLE
Rebuild and publish containers on a regular basis

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp-oci-images#123]
When a new plugin gets released, the single container does not get updated automatically. For now, we should rebuild supported containers automatically on a regular basis (e.g. weekly).

**Comment by keilr** [comment]
will these automatic rebuilds also include back-ported plugin fixes?
e.g. https://github.com/pulp/pulp_python/pull/448

**Comment by daviddavis** [comment]
Yes, we can manually rebuild containers now. But this should automatically rebuild containers with the latest pulpcore/plugin releases. Which would include backported fixes.
