### ISSUE TITLE
Publish Images to Quay.io

### ISSUE THREAD

**Issue by sivel** [pulp/pulp-oci-images#168]
We use the container produced by this repo in the ansible/ansible CI for testing the `ansibe-galaxy` CLI. However, we often hit rate limits with docker.io in AZP.

Is it possible these images could also be pushed to https://quay.io/organization/pulp as well?

Short term, we'll probably have to mirror the version of the container we use into our quay org.

**Comment by fao89** [comment]
we are publishing on github
```
docker pull ghcr.io/pulp/pulp-galaxy-ng:latest
```

On quay.io we already have the operator images, we would need to rename the images to be able to publish them 
https://quay.io/pulp

**Comment by fao89** [comment]
@sivel it is on quay now, but the name changed:
```
docker pull quay.io/pulp/all-in-one-galaxy
```

**Comment by sivel** [comment]
Thanks!
