### ISSUE TITLE
Quay.io images broken

### ISSUE THREAD

**Issue by cityofships** [pulp/pulp-oci-images#199]
```docker run pulp/pulp``` does run; ```docker run quay.io/pulp/pulp``` does not. I see a difference at least in the entrypoint of the working image (`"/init"`) vs. `"/pulp-common-entrypoint.sh"`.

**Comment by fao89** [comment]
`quay.io/pulp/pulp` is a different image, it is used on the operator and compose.
The image you are looking for is: `quay.io/pulp/all-in-one-pulp`

**Comment by cityofships** [comment]
Right - this worked like a charm - thank you. Maybe some small hint in the docs could be added to explain this.
