### ISSUE TITLE
Raise number of task workers to N + 1 number of parallel test runners.

### ISSUE THREAD

**Issue by gerrod3** [pulp/pulp-oci-images#225]
The parallel test runner section of the CI is getting saturated by the number of task workers since most tests require a task to perform some work. @dkliban says the parallel test section uses 8 runners, so 9 task workers should be a good spot to start. One issue could be the container running OOM from having to many simultaneous tasks running, if so we can scale back from there.

**Comment by mdellweg** [comment]
Currently, the workers are started with one service file each. Can we make this a configurable thing?

**Comment by mikedep333** [comment]
I think rather than calling S6 directly, we can call a wrapper script that adjusts this.

I will try that approach.
