### ISSUE TITLE
Layer the pulp images and make pulp/pulp for single processes

### ISSUE THREAD

**Issue by dkliban** [pulp/pulp-oci-images#287]
When a user starts a container using the `pulp/pulp`, the need to be able to specify a specific a service name. When a service name is provided, the container runs just that service. If a service name is not provided, the container launches s6 to manage all the services needed to run Pulp.

**Comment by bmbouter** [comment]
As we implement this the `pulp/pulp` and the operator images feature-wise are getting pretty similar. At what point does it make sense to de-duplicate these assets into one published container?

Here's the summary of what I expect the container to do:

(a) If you start it with no options you get s6 starting all pulp services, nginx reverse proxy, postgresql, and redis
(b) You can add command line options to disable an of ^ services from starting
(c) You should be able to start exactly 1 service without s6 at all, so if the service exits for example the container stops
(d) The existing dynaconf capabilities will allow the user to configure the container to connect to an external postgresql or redis

Right now I think the `pulp/pulp` has (a) and (d) and the operator image (what's the published name for that?) has (b)(c) and (d). Is that the state of things?

**Comment by mikedep333** [comment]
@bmbouter all 4 are my understanding of what we're doing, yes. The container mode will depend on the oci container "CMD".

**Comment by bmbouter** [comment]
@mikedep333 can you identify a little bit about the current state versus what our goals are for a future state? I'm trying to understand what is done versus what needs doing.

Also is deduplicating the `pulp/pulp` and operator images a goal folks have?

**Comment by dkliban** [comment]
Yes, the goal is to have to only one image that can be used by the operator and by anyone wanting to run all services in one container.

**Comment by bmbouter** [comment]
If the operator image is to become `pulp/pulp` then am I right in understanding it needs the s6 layer added to it and then we need to rename it to be published as `pulp/pulp`?

**Comment by mdellweg** [comment]
Do we really want to specify which services not to start? I think at least for the single service per container, we should only specify what service that is. (Let's say we add another type of service, we should not need to reconfigure all the pulpcore-worker containers.)

Am i right understanding that the full minus some service startup would still use s6 but e.g. not start pulpcore-worker, which you can that add as distinct containers using the single service way of startup? So you can scale out e.g. the workers from the single container?

**Comment by dkliban** [comment]
@mdellweg No, we want users to specify which one service to start. If the user doesn't specify which service to run, s6 is used to run all the services.

**Comment by bmbouter** [comment]
I see the benefit of specifying one service and having it start so +1 to that. Consider though a usage where I want the container to run all the Pulp services, but I want to provide my own DB. What do you expect them to specify in that usage?

**Comment by dkliban** [comment]
Right now the single container accepts `PULP_WORKERS` environment variable that controls how many workers `s6` is going to manage.  It would be nice to be able to scale the `pulpcore-content` and `pulpcore-api` services using environment variables also. `PostgreSQL` and `Redis` should also have an environment variable that disables them. 

However, all of these are separate features from this ticket.

**Comment by bmbouter** [comment]
This ticket plans adding a feature that the operator already has (the ability to specify one image). If we combine that with the goal that we're only going to have one built container (instead of the two we have today) then that I think means we're retiring the "operator images" in favor of the single container. If this doesn't sound right, I think it's because it's not. I think instead we're going to:

1. Rename the operator image to be `pulp/pulp`
2. Add whatever changes need to be added to the operator to get (a)(b)(c)(d) possible
3. Fully retire the single container by removing all of it's build things

If we actually do ^ then I think we shouldn't be making additional changes to the single container.

**Comment by dkliban** [comment]
I was being vague in the initial description on purpose. Right now the single container is published as `pulp/pulp` on Dockerhub[0]. The images used by the operator are published on Quay.io as `pulp/pulp`[1]. The goal of this ticket is to publish the same image to everywhere and call it `pulp/pulp`. 

[0] https://hub.docker.com/r/pulp/pulp
[1] https://quay.io/repository/pulp/pulp

**Comment by mikedep333** [comment]
Updating for the current plan, which is reflected here:
https://hackmd.io/8URyo-kXSWapHLfhyfNO2A?both#Proposed-image-layers

**Comment by bmbouter** [comment]
@mikedep333 I'd like to try the image whenever I can. I'm doing some scale testing next week and I want to try the `pulp` image because initially I want all the services, but then as I scale the cluster I want some services disabled and individual containers running specific services.
