### ISSUE TITLE
Add table with images to homepage docs

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulp-oci-images#331]
I think users would benefit from a table on the homepage to help them understand what is offered from a high level. Here's what I think would be helpful, but you tell me what you think would be helpful and doable.

Columns:
* Name - The name (the one name on all the registries)
* Derived From Image - The name of the image this image is based on. This should help users understand the layering that we do.
* Purpose - What does this image do?
* Documentation - A link to a page dedicated to this image showing it's usage and options

**Comment by ipanova** [comment]
s/Derived from Image/ Parent Image/
parent vs base difference https://docs.docker.com/develop/develop-images/baseimages/

**Comment by mikedep333** [comment]
To clarify, this is on the homepage of the OCI image docs, no the main pulp website.

**Comment by mikedep333** [comment]
I moved the layering to here:
https://github.com/pulp/pulp-oci-images/issues/387
