### ISSUE TITLE
Add a page on the `pulp-minimal` image

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulp-oci-images#332]
It should focus on usage (not building currently, assume they are pulling a built image). I imagine it would include:
* An example of running it
* The required options it needs
* Optional options it also has
* How to specify a basic pulp setting

**Comment by git-hyagi** [comment]
Hum... what about a `warning` message that this image is meant to be used by `pulp-operator` and we will not support any usage outside of this scope?

**Comment by bmbouter** [comment]
I'm interpreting the term "support" to mean "intended use". I'm glad you asked because I didn't realize we had differing views on this. Why wouldn't users be able to use the `pulp-minimal` image without using `pulp-operator`?

**Comment by git-hyagi** [comment]
> "I'm interpreting the term "support" to mean "intended use"."

By "support" I was thinking more like: "we are not going to develop features that are not focused on the operator usage".


> " Why wouldn't users be able to use the pulp-minimal image without using pulp-operator?"

Hum... I think that they could, but any modifications or tweaks needed to do so would be out of the scope of our development process?!

Do you think that we should not limit this way (or put this restriction in our development process) and try to achieve "every" kind of usage of the image?

**Comment by bmbouter** [comment]
Yes I didn't image a condition like "really it's for the operator and other usage is not ok". My perspective is that `pulp-minimal` is intended to provide two things:

1) only pulp services (no redis or db installed)
2) only start one service at a time by allow users to specify via options which service should be started.

The pulp-minimal image came from the operator development, so I can see (after this convo) the perception that its purpose is to serve the operator only. I've heard from users and stakeholders who don't use the operator that it's valuable to have an image that provides (1) and (2). Since pulp-minimal does exactly that it seemed natural for the project to broaden it to be a common component that provides (1) and (2) regardless of operator usage. I don't expect the operator developers to be the sole maintainers of `pulp-minimal` image either. My belief is that it's a shared component and with shared usage comes shared maintenance.

What are your thoughts about broadening the intended usage of `pulp-minimal` to just those users who want (1) and (2)?

**Comment by ipanova** [comment]
Let me throw in my take on it.
The layered image effort started so we  solve the separation concern for 2 different groups of users that were identified at the moment. If in the future a 3rd group of users will arise which will not fit into the current design we will need to revisit it which might or might not end up in yet another operand.
I take this ticket request to solely document the required and optional options of the image without speculation of the possible future request and its way of resolution.

**Comment by mikedep333** [comment]
So when we talk about the pulp-minimal image, I assume we mean pulp-web as well.

Based on the example of the docker-compose, here is the overview of what needs to be documented:

For pulp-api/pulp-content/pulp-worker:
1. Setting the "Command" to pulp-api/pulp-content/pulp-worker:
2. Setting the "user" to "pulp"
3. A mounted settings.py with several variables, including the dynamic ones with the host's hostname
4. A mounted database_fields.symmetric.key
5. A mounted/volume for /var/lib/pulp

For pulp-api & pulp-content:
1. Setting env vars POSTGRES_SERVICE_PORT & POSTGRES_SERVICE_HOST

For pulp-api:
1. Setting env var PULP_ADMIN_PASSWORD

For pulp_web:
1. Expose the webserver port
2. A mounted nginx.conf that contains are many settings, and is compatible with the plugin snippets that are baked into the image.

The question then becomes: Do we want to document these, including a giant snippet for nginx.conf?

Or do we want to refer people to our docker-compose.yml and its files (like settings.py), even though there is extra complexity? (Like the fact that we have a different nginx, and we have a wrapper script to modify the snippets to make them compatible with free nginx's dynamic list of backends.

EDIT: After meeting with @dkliban , we agreed to refer users to our docker-compose.yml and its files. We will add separate documentation, or a separate minimal docker-compose.yml, if our docker-compose.yml grows too complex in the future.
