### ISSUE TITLE
Missing UI in pulp/pulp-galaxy-ng

### ISSUE THREAD

**Issue by himdel** [pulp/pulp-oci-images#340]
Seems related to https://github.com/pulp/pulp-oci-images/pull/311, cc @mikedep333 

**Version**
`latest`

**Describe the bug**
pulp-galaxy-ng run with reasonable settings used to serve `/static/galaxy_ng/index.html`, and serve the file also when accessing http root, or /ui.

Now, these URLs just return a 404.

**To Reproduce**

```bash
mkdir settings

echo "\
  ANSIBLE_API_HOSTNAME='http://localhost:8002'
  ANSIBLE_CONTENT_HOSTNAME='http://localhost:8002/api/galaxy/v3/artifacts/collections'
  CONTENT_ORIGIN='http://localhost:8002'
  GALAXY_API_PATH_PREFIX='/api/galaxy/'
  GALAXY_AUTHENTICATION_CLASSES=['rest_framework.authentication.SessionAuthentication', 'rest_framework.authentication.TokenAuthentication']
  GALAXY_DEPLOYMENT_MODE='standalone'
  PULP_CONTENT_PATH_PREFIX='/api/galaxy/v3/artifacts/collections/'
  RH_ENTITLEMENT_REQUIRED='insights'
  TOKEN_AUTH_DISABLED=True
  X_PULP_CONTENT_HOST='localhost'
  GALAXY_REQUIRE_CONTENT_APPROVAL=False
  GALAXY_COLLECTION_SIGNING_SERVICE='ansible-default'
  GALAXY_CONTAINER_SIGNING_SERVICE='container-default'
  GALAXY_FEATURE_FLAGS__container_signing=True
" | sed 's/^\s\+//' | tee settings/settings.py

podman pull ghcr.io/pulp/pulp-galaxy-ng:latest
podman run \
      --publish 8002:80 \
      --volume "$(pwd)/settings":/etc/pulp \
      --tmpfs /var/lib/pulp \
      --tmpfs /var/lib/pgsql \
      --tmpfs /var/lib/containers \
      --device /dev/fuse \
      ghcr.io/pulp/pulp-galaxy-ng:latest
```

Open `http://localhost:8002/` - see missing UI.
Try `curl localhost:8002/static/galaxy_ng/index.html` .. get Not Found.
(API endpoints seem to be responding OK)

**Expected behavior**
Expected to be served `/var/lib/operator/static/galaxy_ng/index.html` (the file is there alright, but nothing serving it).

**Additional context**
Our CI currently relies on having a per backend version container that can then serve static UI built at runtime.
Breaking runtime asset building can be worked around by adding a new layer (making some progress fixing that in https://github.com/ansible/ansible-hub-ui/pull/2765), but we still rely on the container serving these static assets.

Is the change intentional? I assume it's a bug given none of this is mentioned in the changelog, but let me know if not, we do have an alternative approach available :).

**Comment by goosemania** [comment]
@dkliban ^

**Comment by mikedep333** [comment]
@himdel No, it is not intentional.

I am not sure why it is happening. I am looking into it.

**Comment by mikedep333** [comment]
It appears that the static content is not being collected for `pulp-galaxy-ng`, even though it is for `pulp`. It is not being placed into /var/lib/operator/static/ .

This is supposed to happen at build time.

**Comment by himdel** [comment]
https://github.com/ansible/ansible-hub-ui/pull/2765/files is how far I got with that ... seems like collecting assets at build time causes galaxy migrations not to run ¯\\\_(ツ)\_/¯ :)

**Comment by himdel** [comment]
But in the pre-built container, the files do exist .. they just don't get served.

**Comment by mikedep333** [comment]
@himdel I must have been looking at the wrong image or something.

The static content does exist but is not being served like you said. The PR fixes it.
