### ISSUE TITLE
Using Pulp Operator, content-pod is never ready

### ISSUE THREAD

**Issue by Stillbruch** [pulp/pulp-oci-images#399]
**Version**
pulp-minimal:3.21.3 (currently "stable")

**Describe the bug**
When using the Pulp Operator and following the Getting Started manual (https://docs.pulpproject.org/pulp_operator/quickstart/) using the simple.yaml-sample-config to deploy, the "content"-pod never gets in ready state.

**To Reproduce**
See above.

**Expected behavior**
The "content"-pod gets in ready state, as was in pulp-minimal:3.21.2.

**Additional context**
The pod's readiness check runs the script `/usr/bin/readyz.py` which calls either 127.0.0.1:24817 or 127.0.0.1:24816 depending whether the current pod is an API-pod or a content-pod. If an environmental variable named `PULP_CONTENT_WORKERS`exists, it's a content pod. If an environmental variable named `PULP_API_WORKERS` exists, it's an API-pod. The image 3.21.3 seems to "bake" the environmental varible `PULP_API_WORKERS` into the image (see https://quay.io/repository/pulp/pulp-minimal/manifest/sha256:f3ed0ec0c60a0993a3fe6f0a6f6eee20d006faa0759dde8cd216f0aa889f4cd3), which causes the content pod to believe it's an API-pod since apparently the environmental variables are read in alphabetical order.

**Comment by git-hyagi** [comment]
Hi @Stillbruch


Thank you for the investigation and detailed information!

Checking your comment, this seems to be a regression introduced by https://github.com/pulp/pulp-oci-images/pull/395, which is also breaking the operator's pipeline: https://github.com/pulp/pulp-operator/actions/runs/3691374148/jobs/6249312159
