### ISSUE TITLE
Readiness probe failure on cmdline content

### ISSUE THREAD

**Issue by dsavineau** [pulp/pulp-oci-images#402]
**Version**
OCI assets from the `latest` branch (98567b62effa1decd05a0a7b08d308b1111fb601) tested as part of AAP 2.4

**Describe the bug**
Since [1], the pulp type between api and content is determine by reading the `/proc/1/cmdline` file content within the container.

On API pod
```console
$ /usr/bin/readyz.py /api/galaxy/pulp/api/v3/status/
Traceback (most recent call last):
  File "/usr/bin/readyz.py", line 59, in <module>
    if pulp_type() == "[pulp-api]":
  File "/usr/bin/readyz.py", line 55, in pulp_type
    p_type = f.readline().split(" ")[2].strip("\x00")
IndexError: list index out of range
```
On Content pod
```console
$ /usr/bin/readyz.py /pulp/content/
Traceback (most recent call last):
  File "/usr/bin/readyz.py", line 59, in <module>
    if pulp_type() == "[pulp-api]":
  File "/usr/bin/readyz.py", line 55, in pulp_type
    p_type = f.readline().split(" ")[2].strip("\x00")
IndexError: list index out of range
```

However, the output of this file doesn't match what is described in the readyz.py script comment

> gunicorn: master \[pulp-{content,api,worker,resource-manager}\]

There's no space character in the cmdline file.
In fact, that pattern is only applicable for the kernel cmd (`/proc/cmdline`) but not the process cmdline (`/proc/xxx/cmdline`).

On API pod
```console
$ cat /proc/1/cmdline 
/usr/bin/python3.9/usr/bin/gunicorn--bind[::]:24817pulpcore.app.wsgi:application--namepulp-api--timeout90--workers2
```
On Content pod
```console
$ cat /proc/1/cmdline 
/usr/bin/python3.9/usr/bin/gunicornpulpcore.content:server--namepulp-content--bind[::]:24816--worker-classaiohttp.GunicornWebWorker--timeout90--workers2--access-logfile-
```

**To Reproduce**
Deploy pulp-operator with [1] included in the contain image.

**Expected behavior**
API and Content pods in ready state

**Additional context**

[1] https://github.com/pulp/pulp-oci-images/commit/98567b62effa1decd05a0a7b08d308b1111fb601

**Comment by dsavineau** [comment]
Here's the content of the `/proc/1/cmdline` from the python interpreter

```console
>>> with open('/proc/1/cmdline', 'r') as f:
...     cmdline = f.readline()
... 
>>> cmdline
'/usr/bin/python3.9\x00/usr/bin/gunicorn\x00pulpcore.content:server\x00--name\x00pulp-content\x00--bind\x00[::]:24816\x00--worker-class\x00aiohttp.GunicornWebWorker\x00--timeout\x0090\x00--workers\x002\x00--access-logfile\x00-\x00'
```

I don't know if the content is different depending on the environment used (OCP with RHEL 8 based container images)

**Comment by rooftopcellist** [comment]
I was able to build and deploy AAP 2.4 with downstream images and deploy on an x86 cluster.  This is still from the ansible branch, I haven't switched to main for downstream builds yet.

I see this in the content pod logs:
```
[2023-01-26 22:06:54 +0000] [34] [ERROR] Exception in gunicorn worker
Traceback (most recent call last):
File "/usr/lib64/python3.9/site-packages/aiohttp/worker.py", line 57, in run
self.loop.run_until_complete(self._task)
File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
return future.result()
File "/usr/lib64/python3.9/site-packages/aiohttp/worker.py", line 70, in _run
wsgi = await self.wsgi()
File "/usr/lib/python3.9/site-packages/pulpcore/content/__init__.py", line 65, in server
os.chdir(settings.WORKING_DIRECTORY)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/pulp/tmp'
```

And I see the error Dimitri reported with the readyz.py:

```
sh-4.4$ /usr/bin/readyz.py /pulp/content/
Traceback (most recent call last):
  File "/usr/bin/readyz.py", line 59, in <module>
    if pulp_type() == "[pulp-api]":
  File "/usr/bin/readyz.py", line 55, in pulp_type
    p_type = f.readline().split(" ")[2].strip("\x00")
IndexError: list index out of range
```

**Comment by dsavineau** [comment]
for what it worths, it looks like the issue is coming from the gunicorn installation method.

I tested both container images and they are using the same gunicorn version (20.1.0) and with different python runtime (3.8 vs 3.9) but that's not the issue.
The issue is that the upstream image installs gunicorn via pip while the downstream AAP image uses RPM packages.
As a result, the gunicorn entrypoint is different hence the cmdline content variation.

For upstream
```console
$ podman run --rm quay.io/pulp/pulp:latest cat /usr/local/bin/gunicorn
#!/usr/bin/python3.8
# -*- coding: utf-8 -*-
import re
import sys
from gunicorn.app.wsgiapp import run
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run())
```

For downstream
```console
$ podman run --rm <AAP hub 2.4 image> cat /usr/bin/gunicorn
#!/usr/bin/python3.9
# EASY-INSTALL-ENTRY-SCRIPT: 'gunicorn==20.1.0','console_scripts','gunicorn'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'gunicorn==20.1.0'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('gunicorn==20.1.0', 'console_scripts', 'gunicorn')())
```

This is coming from setuptools when creating the RPM package [1]

[1] https://github.com/pypa/setuptools/blob/main/setuptools/command/easy_install.py#L2057-L2090

**Comment by yselkowitz** [comment]
@dsavineau in that case, while the code should still not make any such assumptions about how it is installed, but we could change the RPM build to use pip+wheel instead, which results in a script which matches the first example.
