### ISSUE TITLE
Backport gunicorn env vars change to 3.21

### ISSUE THREAD

**Issue by m-bull** [pulp/pulp-oci-images#403]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to set `PULP_API_WORKERS` and `PULP_CONTENT_WORKERS` in Pulp 3.21 (and earlier) Pulp-in-one containers.

**Describe the solution you'd like**
A backport of https://github.com/pulp/pulp-oci-images/pull/395/commits/29c29df5bf218bfed80a52316356fc0dc89d7bf1 to 3.21- branch(es) please!

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mikedep333** [comment]
This was fixed in #433
