### ISSUE TITLE
status API produces a traceback in the logs 

### ISSUE THREAD

**Issue by dkliban** [pulp/pulp-oci-images#405]
**Version**
quay.io/pulp/pulp latest 728f8846e816 2 weeks ago 2.18 GB

**Describe the bug**
`pulp status` returns just fine but the logs for the container include the following traceback

```
pulp [6881908fdb6c48f4a7140b259276600c]: pulpcore.app.views.status:ERROR: Failed to determine disk usage
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pulpcore/app/views/status.py", line 23, in _disk_usage
    return shutil.disk_usage(default_storage.location)
  File "/usr/lib64/python3.8/shutil.py", line 1258, in disk_usage
    st = os.statvfs(path)
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/pulp/media'
```

**Comment by mikedep333** [comment]
Rather than having the pulpcore code behave differently, pulp-oci-images will just precreate the directory.

**Comment by mikedep333** [comment]
To clarify, does this actually break the container? Or just produce a traceback?
