### ISSUE TITLE
Pulp user does not have permission to create symlinks

### ISSUE THREAD

**Issue by hstct** [pulp/pulp-oci-images#409]
**Describe the bug**
In `pulp_deb` we recently tried to create symlinks of debian packages at run time via `pytest`. See [here](https://github.com/pulp/pulp_deb/pull/704#issuecomment-1375483512). However this results in the following error message:

`PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/site-packages/pulp_deb/tests/functional/data/pool' -> '/usr/local/lib/python3.8/site-packages/pulp_deb/tests/functional/fixtures/debian/pool'`

[Link to the github action](https://github.com/pulp/pulp_deb/actions/runs/3872194493/jobs/6600771907)

This also occurs when trying to run it locally via the `oci-env`.

**To Reproduce**
Create a symlink at runtime (e.g. with `os.symlink()`)

**Comment by decko** [comment]
Would make sense to have those two directories under `/tmp`? We probably will be able to create the symlink but also seems to be the right place to run that operation.

**Comment by mikedep333** [comment]
The reason why symlinks cannot be created there is that the pulp processes run under the pulp user account, and pulp processes should not be able to modify their own code, only their own data.

You can create symlinks somewhere else. We can advise.

-Mike
