### ISSUE TITLE
Add pulp_gem to pulp-oci-images

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulp-oci-images#463]
Please add the released version created [in ticket 85](https://github.com/pulp/pulp_gem/issues/85) to the images so that any user of the images can use the newly updated pulp_gem.

**Comment by mdellweg** [comment]
I think we should move this the OCI-images issue tracker.

**Comment by bmbouter** [comment]
I transferred it.

**Comment by mikedep333** [comment]
We will add it to the stable images once the new version of pulp_gem is released.
