### ISSUE TITLE
Try to setup oci containers: Always stuck with pgsql eorr

### ISSUE THREAD

**Issue by mikch06** [pulp/pulp-oci-images#470]
**Version**
Current containers

**Describe the bug**
After pulling and starting containers immediately stuck with 
postgres: could not access directory "/var/lib/pgsql/data": No such file or directory
Even if i run the container with root or rootless. I created the directories before. 

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by decko** [comment]
@mikch06 Can you write here how you tried to run the container? Which recipe you used?

**Comment by mikch06** [comment]
Hi @decko, thanks for your answer. I tried the official guide. But.... i think it was becuase of selinux! 
I will close this issue.

Thanks a lot
