### ISSUE TITLE
Use python3-createrepo_c and remove some build dependencies

### ISSUE THREAD

**Issue by decko** [pulp/pulp-oci-images#506]
After reading the following note from our `Containerfile.core.base` manifest
```
# The last 5 lines (before clean) are needed until python3-createrepo_c gets an
# RPM upgrade to 0.16.2. Until then, we install & build it from PyPI.
```
I went to `https://pkgs.org/download/python3-createrepo_c` website just to discover that CentOS8 Stream have the version cited in the note.

So, I'm proposing a review of the packages installed into our core image for building and use Pulp.

**Comment by mikedep333** [comment]
Confirm with @dralley

**Comment by dralley** [comment]
We can't use the version in CentOS 8 stream, the comment is a bit out of date, we require a newer version than that.

CentOS 9 stream should work, I think.  But it does remove some flexibility as in the future we will need to wait for the package to be updated before using new functionality, or receiving bugfixes.  In general I think that might be perfectly OK, just be aware of the tradeoff.

**Comment by mikedep333** [comment]
@dralley Yeah, the version in CentOS 8 Stream is 0.17.7.

I'd like to update the comment. What version is needed?

**Comment by dralley** [comment]
0.20.0 is the minimum I believe.

**Comment by decko** [comment]
When we install the python3-createrepo_c package seems that it install the dependencies needed for the build of the createrepo_c package from pypi. With that we can remove the build dependencies and yet keep installed the createrepo_c version from pypi.

What do you think @dralley?

**Comment by dralley** [comment]
Not if the dependencies change between versions, which they do occasionally.  Better to just use an explicit list.

If we update the base image then we can just use the package, but otherwise we shouldn't mix and match.

**Comment by dralley** [comment]
@decko What's the blocker on just updating the base image?  EL9 isn't really bleeding edge anymore.

**Comment by decko** [comment]
I'm gonna close this in favor of #537
