### ISSUE TITLE
Tags don't match the pulpcore version

### ISSUE THREAD

**Issue by newswangerd** [pulp/pulp-oci-images#510]
**Describe the bug**
When I pull `ghcr.io/pulp/pulp:3.24` and run it, `/pulp/api/v3/status/` reports I'm on pulpcore 3.26. Similarly the 3.23 tag is giving me 3.24 and 3.22 gives me 3.23.

**To Reproduce**
Pull an image and check the version on the status api.

**Expected behavior**
The container tag should match the version of pulpcore in the image.

**Comment by mikedep333** [comment]
I thought we fixed it with this commit: https://github.com/pulp/pulp-oci-images/pull/492

**Comment by mikedep333** [comment]
@newswangerd We think that even though #492 was backported, we need to fix other bugs in our old CI 1st.\

@decko and I are working on this.

**Comment by mikedep333** [comment]
I triggered builds for 3.23 through 3.26 after fixing the CI.

Still fixing the 3.22 CI.

**Comment by mikedep333** [comment]
I tested 3.24, it has pulpcore 3.24.1.

Still in the middle of fixing 3.22 CI.

**Comment by decko** [comment]
![image](https://github.com/pulp/pulp-oci-images/assets/20204/316cff91-8940-4e90-b6af-c5d21d65c1f3)

We got the correct version matching the correct tag. Confirmed with 3.22 image.
