### ISSUE TITLE
Pulp docker image tags for releases after pulp 3.43.1 missing

### ISSUE THREAD

**Issue by netsandbox** [pulp/pulp-oci-images#584]
At https://hub.docker.com/r/pulp/pulp docker image tags for pulp releases after 3.43.1 are missing:
https://hub.docker.com/r/pulp/pulp/tags?page=1&name=3.4

**Comment by lubosmj** [comment]
Same for quay.io

https://quay.io/repository/pulp/pulp?tab=tags

**Comment by mikedep333** [comment]
A few of the CI jobs are failing with `pulp: command not found`
https://github.com/pulp/pulp-oci-images/actions/runs/7750046595/job/21136310853#step:12:466

I meant to fix this a few weeks ago before it prevented a release.
