### ISSUE TITLE
OCI images cli tests keep failing.

### ISSUE THREAD

**Issue by mdellweg** [pulp/pulp-oci-images#603]
Instead, I suggest: Install the cli, retrieve it's version and checkout the corresponding release tag to grant access to the matching test suite.

_Originally posted by @mdellweg in https://github.com/pulp/pulp-oci-images/pull/587#discussion_r1477035103_

Currently we run the wrong test suite against the installed version of the CLI, incidentally failing for that reason.

**Comment by mikedep333** [comment]
@mdellweg I didn't originally read the 2nd part of your comment. Yeah, let's do that.

**Comment by markafarrell** [comment]
@mikedep333 @mdellweg I believe that #604 fixes this
