### ISSUE TITLE
ModuleNotFoundError: No module named 'nginx'

### ISSUE THREAD

**Issue by git-hyagi** [pulp/pulp-oci-images#653]
**Version**
pulp-minimal image

**Describe the bug**
The operator is failing to run the `route_paths.py`:
```
sh-5.1$ /usr/bin/route_paths.py content
Traceback (most recent call last):
  File "/usr/bin/route_paths.py", line 7, in <module>
    import nginx
ModuleNotFoundError: No module named 'nginx'
```
which is impacting the deployment of ingress resources.

**Additional context**
I think it is related to:
https://github.com/pulp/pulp-oci-images/commit/264d84029f3836eb705d38dc09a353c4eee7bfe8#diff-96ada1b0cf2d5e352ac9148dd4e446026cac44d852a94669e1e5172b7b2a472bL86

**Comment by mdellweg** [comment]
OK, agree. So this package is not a pulpcore requirement. But it's not listed as a requirement elsewhere, is it?
