### ISSUE TITLE
only arm64 package available for pulp-web:3.22.31 on quay.io

### ISSUE THREAD

**Issue by mgaruccio** [pulp/pulp-oci-images#686]
**Version**
3.22.31

**Describe the bug**
When doing an image pull of the 3.22.31 version of pulp-web from the quay.io repo (also currently tagged as stable) the retrieved image only has an arm64 platform specified in the manifest

**To Reproduce**
- attempt to pull and run the 3.22.31 image from quay.io on an x86 platform
- image will fail to run with a `no match for platform in manifest: not found` error

**Expected behavior**
amd64 image is available and runs when pulling the `stable` and/or 3.22.31 tag

**Additional context**
found this one attempting to deploy pulp via the operator so deploys via that method will be broken until the manifest is corrected.

I did check dockerhub and the correct architecture is available there. 

I was also able to use 3.22.30 from quay without a problem.

**Comment by gerrod3** [comment]
Can you check again, I just fixed this issue for the latest/stable tags, pulp-web should only have amd64 variants, we don't build an arm64 one, yet. Also the 3.22.31 tag should never be the same as the stable/latest and I am not seeing it on any of our published registries.

**Comment by mgaruccio** [comment]
Just checked again and it's working now using the stable tag.  Thanks for the quick resolution here!
