### ISSUE TITLE
Request to rebuild pulp-oci-image 3.13 for a release that includes the latest pulp_rpm plugin (3.13)

### ISSUE THREAD

**Issue by ajsween** [pulp/pulp-oci-images#93]
Due to a bug ([Issue #8825/8807](https://pulp.plan.io/issues/8825)) in the 3.12 version of the pulp_rpm plugin, the publication of certain repos results in an error. This is marked as fixed in the [release notes](https://github.com/pulp/pulp_rpm/blob/3.13/CHANGES.rst) of the pulp_rpm plugin (3.13) via [Issue# 8807](https://pulp.plan.io/issues/8807).

Please rebuild the Pulp 3.13 container so that it pulls the latest release (>=3.13) of the pulp_rpm plugin. The current Pulp 3.13 container release is built using pulp_rpm 3.12.

**Comment by dralley** [comment]
Note to whoever completes this work - due to another pair of bugs in 3.13.0, you should pull in 3.13.1 instead.  Hoping to release that either today or tomorrow.

**Comment by dralley** [comment]
I just pushed a 3.13.1 release, but I realized (sadly, *after* pushing) that there was a third backport that should have been included.

I'll do 3.13.2 and then rebuild the image.

**Comment by dralley** [comment]
Done.  Let me know if you have any further issues @ajsween

**Comment by ajsween** [comment]
I verified everything is working well. Thank you!
